export const FOUND_EMPTY_TEXT = "FOUND_EMPTY_TEXT";
export const FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA";
export const SEARCH_DATA_LOADED = "SEARCH_DATA_LOADED";
export const SHOW_BOOK_DETAIL = "SHOW_BOOK_DETAIL";
export const FETCH_BOOK_DATA = "FETCH_BOOK_DATA";
export const BOOK_DATA_LOADED = "BOOK_DATA_LOADED";

