export const FOUND_EMPTY_TEXT = "FOUND_EMPTY_TEXT";
export const INIT_SEARCH = "INIT_SEARCH";
export const SEARCH_STARTED = "SEARCH_STARTED";
export const SEARCH_DATA_LOADED = "SEARCH_DATA_LOADED";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const SHOW_BOOK_DETAIL = "SHOW_BOOK_DETAIL";
export const FETCH_BOOK_DATA = "FETCH_BOOK_DATA";
export const BOOK_DATA_LOADED = "BOOK_DATA_LOADED";
export const ADD_ARTICLE ="ADD_ARTICLE";

